workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        KEYSTORE_PASSWORD: 123marimba161.
        KEY_ALIAS: marimba
        KEY_PASSWORD: 123marimba161.
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
      - name: Build AAB
        script: ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
